name: Deploy Service

on:
  workflow_dispatch: # Manually trigger the workflow

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '23'

      - name: Install dependencies
        run: npm install
        working-directory: ./API
      
      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Log in to Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Set lowercase image name
        run: |
          echo "IMAGE_NAME=ghcr.io/${GITHUB_REPOSITORY_OWNER,,}/pedidos-api" >> $GITHUB_ENV
      
      - name: Build and push Docker image to GHCR
        uses: docker/build-push-action@v5
        with:
          context: ./API
          file: ./API/Dockerfile
          push: true
          tags: |
            ${{ env.IMAGE_NAME }}:${{ github.sha }}
            ${{ env.IMAGE_NAME }}:latest

      - name: Deploy Bicep to Azure
        uses: azure/arm-deploy@v1
        with:
          subscriptionId: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          resourceGroupName: virtual-pet-backend
          template: ./API/infra/main.bicep
          parameters: >
            appName=virtual-pet-api-${{ github.run_id }}
            dockerImage=${{ env.IMAGE_NAME }}:${{ github.sha }}
            dbUser=${{ secrets.DB_USER }}
            dbPassword=${{ secrets.DB_PASSWORD }}
            dbName=${{ secrets.DB_NAME }}
            dbHost=${{ secrets.DB_HOST }}
            rabbitmqUser=${{ secrets.RABBITMQ_USER }}
            rabbitmqPassword=${{ secrets.RABBITMQ_PASSWORD }}
            rabbitmqHost=${{ secrets.RABBITMQ_HOST }}
            rabbitmqPort=${{ secrets.RABBITMQ_PORT }}
            rabbitmqQueue=deliveries-queue

        