name: Run Migrations

on:
  workflow_dispatch: # Manually trigger the workflowxs

jobs:
  run-migrations:
    runs-on: ubuntu-latest
    
    env:
      DB_USER: ${{ secrets.DB_USER }}
      DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
      DB_NAME: ${{ secrets.DB_NAME }}
      DB_HOST: ${{ secrets.DB_HOST }} 
      NODE_ENV: development
    
    steps:
        - name: Checkout code
          uses: actions/checkout@v4

        - name: Set up Node.js
          uses: actions/setup-node@v4
          with:
            node-version: '23'

        - name: Install dependencies
          run: npm install
          working-directory: ./API

        - name: Run migrations
          run: npx sequelize-cli db:migrate
          working-directory: ./API
        
        - name: Run seeders
          run: npx sequelize-cli db:seed:all
          working-directory: ./API
